### ISSUE TITLE
Wrong translation for "xyz hat die TAGNAME Thema entfernt"

### ISSUE THREAD

**Issue by wolfgang-demeter** [flarum-lang/german#48]
I guess those are remnants from back when **tag** was translated to **Kategorie** and not **Thema**, but **die** was not changed to **das**, or was only tested with multiple tags, where **das** would be wrong again.

![grafik](https://user-images.githubusercontent.com/4437946/147817576-ef1b60e7-6a72-4ac8-964c-bf46a52c61c6.png)
![grafik](https://user-images.githubusercontent.com/4437946/147817616-409321aa-cb06-4374-9cdd-6e05dcba2ad6.png)

Btw. i'd much prefer the translation **{username} hat das Thema TAGNAME entfernt/hinzugefügt** instead of **{username} hat das TAGNAME Thema entfernt/hinzugefügt**.

So if `{tagAdded}` and `{tagRemoved}` are translated with `flarum-tags.forum.post_stream.tags_text` - i'm just guessing - it had to look something like that in [locale/flarum-tags.yml](https://github.com/flarum-lang/german/blob/master/locale/flarum-tags.yml):
```yaml
flarum-tags
  forum
    post_stream:
      added_and_removed_tags_text: '{username} hat {tagsAdded} hinzugefügt und {tagsRemoved} entfernt.'
      added_tags_text: '{username} hat {tagsAdded} hinzugefügt.'
      removed_tags_text: '{username} hat {tagsRemoved} entfernt.'
      tags_text: '{count, plural, one {das Thema {tags}} other {die Themen {tags}}}'
```
